name: Check Podcast Status

on:
  schedule:
    # Lịch chạy mỗi giờ
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub UI

jobs:
  check-podcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install curl jq

      - name: Check Podcast Status
        run: |
          PODCAST_URL="https://podcasts.apple.com/us/podcast/backlink1dpod/id1786769245"
          TELEGRAM_TOKEN="7904092565:AAFsSnZaZT8fZcYO587LxRm4tFROvNE2bsQ"
          CHAT_ID="7066164129"

          # Kiểm tra trạng thái podcast
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null $PODCAST_URL)

          if [ "$RESPONSE" -eq 200 ]; then
            echo "Podcast hoạt động bình thường."
          else
            echo "Podcast cần được publish lại."
            # Gửi thông báo đến Telegram nếu podcast không hoạt động
            curl -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
              -d chat_id=$CHAT_ID \
              -d text="Podcast bị lỗi: Cần được publish lại."
          fi
