name: Check & Auto-Publish Podcast

on:
  schedule:
    - cron: '*/15 * * * *'  # Kiểm tra mỗi 15 phút
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub UI

jobs:
  check-podcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq chromium-chromedriver
          pip install playwright
          playwright install chromium

      - name: Check Podcast Status
        run: |
          PODCAST_URL="https://podcasts.apple.com/us/podcast/backlink1dpod/id1786769245"
          TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}"
          CHAT_ID="${{ secrets.CHAT_ID }}"

          echo "🔍 Checking Podcast Status..."
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" $PODCAST_URL)

          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Podcast đang hoạt động bình thường!"
          else
            echo "❌ Podcast không hoạt động, cần publish lại!"
            curl -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
              -d chat_id=$CHAT_ID \
              -d text="⚠ Podcast bị lỗi: cần publish lại!"

            # Kích hoạt workflow publish_podcast.yml
            curl -X POST -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish_podcast.yml/dispatches \
              -d '{"ref":"main"}'
